# Generated by Django 5.2.8 on 2025-12-17 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Matrícula')),
                ('turma', models.CharField(max_length=50, verbose_name='Turma')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureza', models.CharField(choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=10)),
                ('tipo', models.CharField(choices=[('Disciplinar', 'Disciplinar'), ('Pedagogico', 'Pedagógico')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=100, verbose_name='O que aconteceu?')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aluno', verbose_name='Aluno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fato Observado',
                'verbose_name_plural': 'Fatos Observados',
                'ordering': ['-data_registro'],
            },
        ),
    ]
