# Generated by Django 6.0 on 2025-12-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='serie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turma',
            field=models.CharField(max_length=50, verbose_name='Turma'),
        ),
    ]
