# Generated by Django 6.0 on 2026-01-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='serie',
            field=models.CharField(choices=[('6º', '6º'), ('7º', '7º'), ('8º', '8º'), ('9º', '9º'), ('1ª', '1ª'), ('2ª', '2ª'), ('3ª', '3ª')], max_length=20, verbose_name='Série'),
        ),
    ]
