# Generated by Django 5.2.8 on 2025-12-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default='', max_length=20, verbose_name='Matrícula'),
            preserve_default=False,
        ),
    ]
