# Generated by Django 5.2.8 on 2026-01-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_turma_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fo',
            name='titulo',
            field=models.CharField(choices=[('Participação em aula', 'Participação em aula'), ('Comportamento exemplar', 'Comportamento exemplar'), ('Atraso', 'Atraso'), ('Falta de material', 'Falta de material'), ('Distração', 'Distração'), ('Outro', 'Outro')], max_length=100, verbose_name='O que aconteceu?'),
        ),
    ]
