# Generated by Django 5.2.8 on 2026-01-09 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_fo_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fo',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='fo',
            name='evidencias',
            field=models.TextField(blank=True, null=True, verbose_name='Evidências (links ou descrições)'),
        ),
        migrations.AddField(
            model_name='fo',
            name='relatorio',
            field=models.TextField(blank=True, null=True, verbose_name='Relatório'),
        ),
        migrations.AddField(
            model_name='fo',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fo_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='fo',
            name='status',
            field=models.CharField(choices=[('Em aberto', 'Em aberto'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], default='Em aberto', max_length=20, verbose_name='Status'),
        ),
    ]
