# Generated by Django 5.2.8 on 2026-01-09 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_fohistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('fo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='home.fo')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
        ),
    ]
