# Generated by Django 5.2.8 on 2026-01-09 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colegio', models.CharField(blank=True, default='', max_length=100, verbose_name='Nome do Colégio')),
            ],
            options={
                'verbose_name': 'Colégio',
                'verbose_name_plural': 'Colégios',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=20, verbose_name='Série')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.colegio', verbose_name='Colégio')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureza', models.CharField(choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=10)),
                ('tipo', models.CharField(choices=[('Disciplinar', 'Disciplinar'), ('Pedagogico', 'Pedagógico')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(choices=[('Participação em aula', 'Participação em aula'), ('Comportamento exemplar', 'Comportamento exemplar'), ('Atraso', 'Atraso'), ('Falta de material', 'Falta de material'), ('Distração', 'Distração'), ('Outro', 'Outro')], max_length=100, verbose_name='O que aconteceu?')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('status', models.CharField(choices=[('Em aberto', 'Em aberto'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], default='Em aberto', max_length=20, verbose_name='Status')),
                ('relatorio', models.TextField(blank=True, null=True, verbose_name='Relatório')),
                ('evidencias', models.TextField(blank=True, null=True, verbose_name='Evidências (links ou descrições)')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aluno', verbose_name='Aluno')),
                ('colegio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.colegio', verbose_name='Colégio')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fo_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fato Observado',
                'verbose_name_plural': 'Fatos Observados',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('fo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='home.fo')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
        ),
        migrations.CreateModel(
            name='FOHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('campo_alterado', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('fo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='home.fo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de F.O.',
                'verbose_name_plural': 'Históricos de F.O.',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(choices=[('6º', '6º'), ('7º', '7º'), ('8º', '8º'), ('9º', '9º'), ('1ª', '1ª'), ('2ª', '2ª'), ('3ª', '3ª')], max_length=20, verbose_name='Série')),
                ('turma', models.CharField(max_length=50, verbose_name='Turma')),
                ('colegio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.colegio', verbose_name='Colégio')),
                ('professor', models.ManyToManyField(related_name='turmas', to=settings.AUTH_USER_MODEL, verbose_name='Professores Responsáveis')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'unique_together': {('serie', 'turma', 'colegio')},
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.turma', verbose_name='Turma'),
        ),
    ]
