# Generated by Django 5.2.8 on 2026-01-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fo',
            name='serie_original',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Série na época'),
        ),
        migrations.AddField(
            model_name='fo',
            name='turma_original',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Turma na época'),
        ),
    ]
