# Generated by Django 5.2.8 on 2026-01-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_fo_serie_original_fo_turma_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='fo',
            name='colegio_original',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Colégio na época'),
        ),
    ]
