# Generated by Django 5.2.8 on 2026-01-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_fo_colegio_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fo',
            name='colegio_original',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Colégio na época'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='serie_original',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Série na época'),
        ),
        migrations.AlterField(
            model_name='fo',
            name='turma_original',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Turma na época'),
        ),
    ]
