# Generated by Django 5.2.8 on 2026-01-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_fo_intensidade_alter_fo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fo',
            name='status',
            field=models.CharField(choices=[('Em aberto', 'Em aberto'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Anulado', 'Anulado')], default='Em aberto', max_length=20, verbose_name='Status'),
        ),
    ]
