# Generated by Django 5.2.8 on 2025-12-16 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureza', models.CharField(choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=10)),
                ('nome_aluno', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=20)),
                ('turma', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
