name: 🚀 Deploy via SSH (VPS)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 📡 Executar comandos no VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.FTP_SERVER }}      
        username: ${{ secrets.FTP_USER }} 
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22022 
        script_stop: true
        script: |
          echo "Buscando atualizações do GitHub..."
          cd /home/wwutiu/utiusys.com.br/GTX1650/public_html/spectra_1.1
          
          # Força o código local a ficar idêntico ao repositório main
          git fetch origin main 
          git reset --hard origin/main
          
          echo "Configurando ambiente virtual..."
          VENV_NAME="venv_312"
          
          if [ ! -d "$VENV_NAME" ]; then
              echo "Criando novo ambiente isolado $VENV_NAME..."
              python3.12 -m venv $VENV_NAME
          fi

          source $VENV_NAME/bin/activate
          
          echo "Instalando dependências..."
          pip install --upgrade pip
          pip install -r requirements.txt
          
          echo "Atualizando arquivos estáticos e banco de dados..."
          python manage.py collectstatic --noinput
          python manage.py migrate
          
          echo "Reiniciando a aplicação..."
          touch index.cgi 
          
          echo "✅ Deploy Finalizado com Sucesso!"
