name: 🚀 Deploy via SSH (VPS)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Obter código
      uses: actions/checkout@v4

    - name: 📡 Executar comandos no VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST_IP }}      
        username: ${{ secrets.HOST_USER }} 
        server: ${{ secrets.FTP_SERVER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/utiusys/public_html/spectra_1.1
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py collectstatic --noinput
          python manage.py migrate
          mkdir -p tmp
          touch tmp/restart.txt
          
          echo "✅ Deploy Finalizado com Sucesso!"

        exclude: |
          **/.git*
          **/.github*
          **/node_modules/**
          README.md
          **/venv/**
          **/*.log
          .htaccess
          passenger_wsgi.py
